### ISSUE TITLE
update deletion

### ISSUE THREAD

**Issue by jeknov** [KseniaShkaruta/Automatic-Speech-Recognition-for-AD#1]
## Details
Update DELETION 

## To do
*A list of items that this issue should cover.*
- [x] add *.py extension to the file
- [x] function word_count : 1) do not return print (line 22), just cnt, so it can be used for later calculations; 2) you don't need length of sublist['tokens'] here, can simplify it to "for each in sublist['tokens']: if each['type'] == 'word':" 
- [x] you can get min/max/other stats with one command scipy.stats.describe(list_name) but that should be a numpy list

**Comment by LLMsKsenia** [comment]
resolved via request #2
